
DATA_FILE = r"C:\Users\Pacific\Desktop\Fall2017\COMP151_AI\project1\genAlgData1.txt"

NUM_OF_INITIAL_CHROM = 50

NUM_OF_CHROM_PER_GEN = 50

NUM_OF_GENERATIONS = 48

PERCENTAGE_OF_SELECTION = 0.33

CROSS_TYPE = 'kpoint'

MUTATION_RATE = 70

MUTATION_RATE_CHANGE_PER_GEN = 0.5

MUTATION_TYPE = 'fixed'

SELECTION_TYPE = 'tournament'

